#:schema node_modules/wrangler/config-schema.json
name = "cf-agent-dispatch"
main = "src/index.ts"
compatibility_date = "2025-02-26"

[[dispatch_namespaces]]
binding = "TENANT"
namespace = "cf-agent-tenants"
